{{- if .Values.usearch.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "universal-search.componentFullname" (dict "Release" .Release "Chart" .Chart "Values" .Values "component" "api") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "universal-search.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "api") | nindent 4 }}
data:
  {{- range $key, $value := .Values.usearch.api.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
