{{- if and .Values.usearch.api.enabled (eq .Values.secrets.backend "externalSecrets") .Values.usearch.api.secretEnv }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "universal-search.componentFullname" (dict "Release" .Release "Chart" .Chart "Values" .Values "component" "api") }}-externalsecret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "universal-search.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "api") | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.secrets.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "universal-search.componentFullname" (dict "Release" .Release "Chart" .Chart "Values" .Values "component" "api") }}-secret
    creationPolicy: Owner
  data:
    {{- range $key, $value := .Values.usearch.api.secretEnv }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $.Values.secrets.externalSecrets.secretStoreRef.name }}/{{ $key }}
    {{- end }}
{{- end }}
