{{- if and .Values.usearch.api.enabled .Values.usearch.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "universal-search.componentFullname" (dict "Release" .Release "Chart" .Chart "Values" .Values "component" "api") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "universal-search.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "api") | nindent 4 }}
  {{- with .Values.usearch.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.usearch.api.ingress.className }}
  {{- with .Values.usearch.api.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.usearch.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "universal-search.componentFullname" (dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" "api") }}
                port:
                  number: {{ $.Values.usearch.api.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
