# SPEC-EVAL-002 REQ-EVAL2-007: Grafana datasource auto-provisioning.
# The uid "prometheus" matches the datasource uid referenced by
# deploy/grafana/dashboards/adapter-reliability.json.
apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
