#!/usr/bin/env bash
# scripts/gen-deps-manifest.sh — Idempotent dependency manifest generator
# SPEC-DEP-001 REQ-DEP-007
#
# Usage: bash scripts/gen-deps-manifest.sh
#
# Concatenates static header + dynamic sections into docs/dependencies.md.
# Sections that require local tooling (Go, uv, pnpm) produce TODO placeholders
# when the tooling or lock files are not present (safe for CI with no deps installed).
#
# Idempotent: re-running on a clean tree produces no diff.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT="${ROOT}/docs/dependencies.md"
HEADER="${ROOT}/docs/_deps-header.md"
COMPOSE_TABLE="${ROOT}/docs/_deps-compose-table.md"

# Verify required static files exist
if [ ! -f "${HEADER}" ]; then
  echo "ERROR: ${HEADER} not found. Cannot generate manifest." >&2
  exit 1
fi
if [ ! -f "${COMPOSE_TABLE}" ]; then
  echo "ERROR: ${COMPOSE_TABLE} not found. Cannot generate manifest." >&2
  exit 1
fi

{
  # ── Static preamble (policy, allowlist, compose table instructions) ─────────
  cat "${HEADER}"

  # ── Go Dependencies ─────────────────────────────────────────────────────────
  echo "## Go Dependencies"
  echo ""
  echo "<!-- generated by scripts/gen-deps-manifest.sh -->"
  if [ -f "${ROOT}/go.sum" ] && command -v go >/dev/null 2>&1; then
    echo '```'
    (cd "${ROOT}" && go list -m all 2>/dev/null)
    echo '```'
  else
    echo '```'
    echo "# TODO: run 'go list -m all' after Go toolchain is installed"
    echo "# go.sum not present or 'go' binary not found"
    echo '```'
  fi
  echo ""

  # ── Python Dependencies (per service) ───────────────────────────────────────
  echo "## Python Dependencies (per service)"
  echo ""
  echo "<!-- generated by scripts/gen-deps-manifest.sh -->"
  found_svc=false
  for svc_dir in "${ROOT}/services"/*/; do
    [ -f "${svc_dir}pyproject.toml" ] || continue
    svc_name="$(basename "${svc_dir}")"
    found_svc=true
    echo "### ${svc_name}"
    echo ""
    if command -v uv >/dev/null 2>&1 && [ -d "${svc_dir}.venv" ]; then
      echo '```'
      (cd "${svc_dir}" && uv pip freeze 2>/dev/null)
      echo '```'
    else
      echo '```'
      echo "# TODO: run 'uv pip freeze' in services/${svc_name}/ after uv install"
      echo "# .venv not present or 'uv' binary not found"
      echo '```'
    fi
    echo ""
  done
  if [ "${found_svc}" = false ]; then
    echo '```'
    echo "# TODO: no services with pyproject.toml found"
    echo '```'
    echo ""
  fi

  # ── Web Dependencies ─────────────────────────────────────────────────────────
  echo "## Web Dependencies"
  echo ""
  echo "<!-- generated by scripts/gen-deps-manifest.sh -->"
  if command -v pnpm >/dev/null 2>&1 && [ -d "${ROOT}/web/node_modules" ]; then
    echo '```'
    (pnpm --dir "${ROOT}/web" list --depth=0 2>/dev/null)
    echo '```'
  else
    echo '```'
    echo "# TODO: run 'pnpm --dir web list --depth=0' after pnpm install"
    echo "# node_modules not present or 'pnpm' binary not found"
    echo '```'
  fi
  echo ""

  # ── Static Compose Services table ───────────────────────────────────────────
  cat "${COMPOSE_TABLE}"

} > "${OUT}"

echo "Generated: ${OUT}"
